export const SELECCIONAR_PACIENTE = 'SELECCIONAR_PACIENTE';
export const SELECCIONAR_CAMA = 'SELECCIONAR_CAMA';
export const SELECCIONAR_MICROORGANISMO = 'SELECCIONAR_MICROORGANISMO';
export const SELECCIONAR_ANTIBIOTICO = 'SELECCIONAR_ANTIBIOTICO';

