export const SELECCIONAR_PACIENTE = 'SELECCIONAR_PACIENTE';
export const SELECCIONAR_CAMA = 'SELECCIONAR_CAMA';
export const SELECCIONAR_MICROORGANISMO = 'SELECCIONAR_MICROORGANISMO';
export const SELECCIONAR_ANTIBIOTICO = 'SELECCIONAR_ANTIBIOTICO';
export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';