
export const microorganismoOptions = [
    { value: 'Negativo', label: 'Negativo' },
    { value: 'Acinetobacter', label: 'Acinetobacter' },
    { value: 'Burkholderia', label: 'Burkholderia' },
    { value: 'Chlamydophila pneumoniae', label: 'Chlamydophila pneumoniae' },
    { value: 'Clostridium difficile', label: 'Clostridium difficile' },
    { value: 'Enterobacter spp', label: 'Enterobacter spp' },
    { value: 'Escherichia coli', label: 'Escherichia coli' },
    { value: 'Haemophilus influenzae', label: 'Haemophilus influenzae' },
    { value: 'Klebsiella', label: 'Klebsiella' },
    { value: 'Legionella', label: 'Legionella' },
    { value: 'Moraxella catarrhalis', label: 'Moraxella catarrhalis' },
    { value: 'Mycobacterium tuberculosis', label: 'Mycobacterium tuberculosis' },
    { value: 'Mycobacterias No tuberculosis', label: 'Mycobacterias No tuberculosis' },
    { value: 'Mycoplasma pneumoniae', label: 'Mycoplasma pneumoniae' },
    { value: 'Neisseria meningitidis', label: 'Neisseria meningitidis' },
    { value: 'Pseudomonas aeruginosa', label: 'Pseudomonas aeruginosa' },
    { value: 'Serratia', label: 'Serratia' },
    { value: 'Staphylococcus aureus', label: 'Staphylococcus aureus' },
    { value: 'Stenotrophomonas', label: 'Stenotrophomonas' },
    { value: 'Streptococcus agalactiae', label: 'Streptococcus agalactiae' },
    { value: 'Streptococcus pneumoniae', label: 'Streptococcus pneumoniae' },
    { value: 'Streptococcus pyogenes', label: 'Streptococcus pyogenes' },

    { value: 'Coronavirus', label: 'Coronavirus' },
    { value: 'Coronavirus SARS-CoV-2 (COVID)', label: 'Coronavirus SARS-CoV-2 (COVID)' },
    { value: 'Coronavirus 229E', label: 'Coronavirus 229E' },
    { value: 'Coronavirus NL63', label: 'Coronavirus NL63' },
    { value: 'Coronavirus OC43', label: 'Coronavirus OC43' },
    { value: 'Coronavirus HKU1', label: 'Coronavirus HKU1' },
    { value: 'Enterovirus/Rinovirus', label: 'Enterovirus/Rinovirus' },
    { value: 'Influenza A', label: 'Influenza A' },
    { value: 'Influenza A H1N1', label: 'Influenza A H1N1' },
    { value: 'Influenza A H3N2', label: 'Influenza A H3N2' },
    { value: 'Influenza B', label: 'Influenza B' },
    { value: 'Metapneumovirus', label: 'Metapneumovirus' },
    { value: 'Parainfluenza 1', label: 'Parainfluenza 1' },
    { value: 'Parainfluenza 2', label: 'Parainfluenza 2' },
    { value: 'Parainfluenza 3', label: 'Parainfluenza 3' },
    { value: 'Parainfluenza 4', label: 'Parainfluenza 4' },
    { value: 'Virus de Epstein-Barr', label: 'Virus de Epstein-Barr' },
    { value: 'Virus Hepatitis B', label: 'Virus Hepatitis B' },
    { value: 'Virus Hepatitis C', label: 'Virus Hepatitis C' },
    { value: 'Virus Herpes Simple', label: 'Virus Herpes Simple' },
    { value: 'Virus Herpes Zoster', label: 'Virus Herpes Zoster' },
    { value: 'VIH', label: 'VIH' },
    { value: 'Virus Sincitial Respiratorio (VSR)', label: 'Virus Sincitial Respiratorio (VSR)' },

    { value: 'Aspergillus', label: 'Aspergillus' },
    { value: 'Blastomyces dermatitidis', label: 'Blastomyces dermatitidis' },
    { value: 'Candida', label: 'Candida' },
    { value: 'Coccidioides immitis', label: 'Coccidioides immitis' },
    { value: 'Cryptococcus neoformans', label: 'Cryptococcus neoformans' },
    { value: 'Histoplasma capsulatum', label: 'Histoplasma capsulatum' },
    { value: 'Mucorales', label: 'Mucorales' },
    { value: 'Pneumocystis jirovecii', label: 'Pneumocystis jirovecii' },
 
    // Más opciones...
  ];


export const microorganismoOptionsMuestra = [
  { value: 'LB03 Otico', label: 'LB03 Otico' },
  { value: 'LB04 Ocular', label: 'LB04 Ocular' },
  { value: 'LB05 Otros exudados', label: 'LB05 Otros exudados' },
  { value: 'LB06 Expectoración, piogenos (inducida y supervisada)', label: 'LB06 Expectoración, piogenos (inducida y supervisada)' },
  { value: 'LB07 Cultivo, aspirado bronquial (con sonda)', label: 'LB07 Cultivo, aspirado bronquial (con sonda)' },
  { value: 'LB08 Cultivo, lavado bronquioloalveolar (FBC)', label: 'LB08 Cultivo, lavado bronquioloalveolar (FBC)' },
  { value: 'LB09 Pleural', label: 'LB09 Pleural' },
  { value: 'LB10 Cefalorraquídeo', label: 'LB10 Cefalorraquídeo' },
  { value: 'LB11 Otros líquidos corporales', label: 'LB11 Otros líquidos corporales' },
  { value: 'LB12 Hemocultivos (Bacteria)', label: 'LB12 Hemocultivos (Bacteria)' },
  { value: 'LB13 Mielocultivo bacterias', label: 'LB13 Mielocultivo bacterias' },
  { value: 'LB14 Hemocultivo micobacterias', label: 'LB14 Hemocultivo micobacterias' },
  { value: 'LB15 Coprocultivo', label: 'LB15 Coprocultivo' },
  { value: 'LB16 Urocultivo', label: 'LB16 Urocultivo' },
  { value: 'LB17 Heridas abiertas', label: 'LB17 Heridas abiertas' },
  { value: 'LB18 Punción estéril', label: 'LB18 Punción estéril' },
  { value: 'LB19 Biopsia', label: 'LB19 Biopsia' },
  { value: 'LB20 Punta de catéter', label: 'LB20 Punta de catéter' },
  { value: 'LB21 Otras secreciones', label: 'LB21 Otras secreciones' },
  { value: 'LB22 Baciloscopia (Bacilo de Koch)', label: 'LB22 Baciloscopia (Bacilo de Koch)' },
  { value: 'LB25 Cultivo de hongos', label: 'LB25 Cultivo de hongos' },
  { value: 'LB27 Inmunofluorescencia para Pneumocistis Jirovecii', label: 'LB27 Inmunofluorescencia para Pneumocistis Jirovecii' },
  { value: 'LB28 Detección de Cryptococcus', label: 'LB28 Detección de Cryptococcus' },
  { value: 'LB30 PCR para tuberculosis', label: 'LB30 PCR para tuberculosis' },
  { value: 'LB39 PCR para virus influenza (A-B)', label: 'LB39 PCR para virus influenza (A-B)' },
  { value: 'LB39A PCR SARS-COV-2', label: 'LB39A PCR SARS-COV-2' },
  { value: 'LB42 PCR / Detección de herpes virus', label: 'LB42 PCR / Detección de herpes virus' },
  { value: 'LB43 PCR para aspergillus sp', label: 'LB43 PCR para aspergillus sp' },
  { value: 'LB45 Mielocultivo micobacterias', label: 'LB45 Mielocultivo micobacterias' },
  { value: 'LB46 Cultivo de micobacterias y prueba de susceptibilidad de M. tuberculosis', label: 'LB46 Cultivo de micobacterias y prueba de susceptibilidad de M. tuberculosis' },
  { value: 'LB47 Tinciones especiales para búsqueda de hongos', label: 'LB47 Tinciones especiales para búsqueda de hongos' },
  { value: 'LB48 Detección de Histoplasma', label: 'LB48 Detección de Histoplasma' },
  { value: 'LB49 Detección de C. Immitis', label: 'LB49 Detección de C. Immitis' },
  { value: 'LB50 Toxina AB C. Difficile', label: 'LB50 Toxina AB C. Difficile' },
  { value: 'LB51 PCR bacteriano respiratorio', label: 'LB51 PCR bacteriano respiratorio' },
  { value: 'LB52 PCR viral respiratorio', label: 'LB52 PCR viral respiratorio' },
  { value: 'LB53 Genotipificación de micobacterias / identificación', label: 'LB53 Genotipificación de micobacterias / identificación' },
  { value: 'LB54 Genotipificación de micobacterias / drogosusceptibilidad', label: 'LB54 Genotipificación de micobacterias / drogosusceptibilidad' },
  { value: 'LB55 Detección de Galactomanano - Aspergillus', label: 'LB55 Detección de Galactomanano - Aspergillus' },
  { value: 'LB57 Ensayo de liberación interferon gamma (Quantiferon)', label: 'LB57 Ensayo de liberación interferon gamma (Quantiferon)' },
  { value: 'LB58 Detección de antígeno de Legionella pneumophila en orina', label: 'LB58 Detección de antígeno de Legionella pneumophila en orina' },
  { value: 'LB59 Panel de Sepsis', label: 'LB59 Panel de Sepsis' },
  { value: 'LB60 Panel Meningitis', label: 'LB60 Panel Meningitis' },
  { value: 'LB61 Panel gastrointestinal', label: 'LB61 Panel gastrointestinal' }
  // Más opciones...
];