
export const diagnosticoOptions = [
  { value: 'Absceso de profundo de cuello', label: 'Absceso profundo de cuello' },
  { value: 'Absceso de superficial de cuello', label: 'Absceso superficial de cuello' },
  { value: 'Absceso periamigdalino', label: 'Absceso periamigdalino' },
  { value: 'Absceso pulmonar', label: 'Absceso pulmonar' },
  { value: 'Absceso retrofaríngeo o parafaríngeo', label: 'Absceso retrofaríngeo o parafaríngeo' },
  { value: 'Acidosis Metabólica', label: 'Acidosis Metabólica' },
  { value: 'Acidosis Respiratoria', label: 'Acidosis Respiratoria' },
  { value: 'Alcalosis Metabólica', label: 'Alcalosis Metabólica' },
  { value: 'Alcalosis Respiratoria', label: 'Alcalosis Respiratoria' },
  { value: 'Amigdalitis aguda', label: 'Amigdalitis aguda' },
  { value: 'Amiotrofia espinal', label: 'Amiotrofia espinal' },
  { value: 'Angina de pecho', label: 'Angina de pecho' },
  { value: 'Artritis psoriasica', label: 'Artritis psoriasica' },
  { value: 'Artritis reumatoide', label: 'Artritis reumatoide' },
  { value: 'Asma alérgica', label: 'Asma alérgica' },
  { value: 'Asma inducida por el ejercicio', label: 'Asma inducida por el ejercicio' },
  { value: 'Asma ocupacional', label: 'Asma ocupacional' },
  { value: 'Asma', label: 'Asma' },
  { value: 'Atelectasia', label: 'Atelectasia' },
  { value: 'Bronquiectasias asociadas a Discinesia ciliar', label: 'Bronquiectasias asociadas a Discinesia ciliar' },
  { value: 'Bronquiectasias asociadas a Enfermedad del cilio inmóvil', label: 'Bronquiectasias asociadas a Enfermedad del cilio inmóvil' },
  { value: 'Bronquiectasias asociadas a Fibrosis quística', label: 'Bronquiectasias asociadas a Fibrosis quística' },
  { value: 'Bronquiectasias asociadas a Inmunodeficiencia común variable', label: 'Bronquiectasias asociadas a Inmunodeficiencia común variable' },
  { value: 'Bronquiectasias asociadas a Síndrome de Kartagener', label: 'Bronquiectasias asociadas a Síndrome de Kartagener' },
  { value: 'Bronquiectasias asociadas a Síndrome de Young', label: 'Bronquiectasias asociadas a Síndrome de Young' },
  { value: 'Bronquiectasias', label: 'Bronquiectasias' },
  { value: 'Cancer Pulmonar - Adenocarcinoma pulmonar', label: 'Cancer Pulmonar - Adenocarcinoma pulmonar' },
  { value: 'Cancer Pulmonar - Carcinoma de células pequeñas', label: 'Cancer Pulmonar - Carcinoma de células pequeñas' },
  { value: 'Cancer Pulmonar - Carcinoma epidermoide', label: 'Cancer Pulmonar - Carcinoma epidermoide' },
  { value: 'Cancer Pulmonar - Linfoma pulmonar', label: 'Cancer Pulmonar - Linfoma pulmonar' },
  { value: 'Cancer Pulmonar - Tumor carcinoide', label: 'Cancer Pulmonar - Tumor carcinoide' },
  { value: 'Choque cardiogénico', label: 'Choque cardiogénico' },
  { value: 'Choque distributivo', label: 'Choque distributivo' },
  { value: 'Choque hipovolémico', label: 'Choque hipovolémico' },
  { value: 'Choque obstructivo', label: 'Choque obstructivo' },
  { value: 'Choque séptico', label: 'Choque séptico' },
  { value: 'Colitis ulcerativa', label: 'Colitis ulcerativa' },
  { value: 'Cor Pulmonale', label: 'Cor Pulmonale' },
  { value: 'Crisis asmática (1era vez)', label: 'Crisis asmática (1era vez)' },
  { value: 'Crisis asmática (Subsecuente)', label: 'Crisis asmática (Subsecuente)' },
  { value: 'Cáncer de colon', label: 'Cáncer de colon' },
  { value: 'Cáncer de páncreas', label: 'Cáncer de páncreas' },
  { value: 'Cáncer gástrico', label: 'Cáncer gástrico' },
  { value: 'Demencia con cuerpos de Lewy', label: 'Demencia con cuerpos de Lewy' },
  { value: 'Demencia vascular', label: 'Demencia vascular' },
  { value: 'Derrame Pleural Bilateral', label: 'Derrame Pleural Bilateral' },
  { value: 'Derrame Pleural Complicado', label: 'Derrame Pleural Complicado' },
  { value: 'Derrame Pleural Maligno', label: 'Derrame Pleural Maligno' },
  { value: 'Derrame Pleural Paraneoplásico', label: 'Derrame Pleural Paraneoplásico' },
  { value: 'Derrame Pleural Paraneumónico', label: 'Derrame Pleural Paraneumónico' },
  { value: 'Derrame Pleural Tuberculoso', label: 'Derrame Pleural Tuberculoso' },
  { value: 'Derrame Pleural secundario a Enfermedad autoinmune', label: 'Derrame Pleural secundario a Enfermedad autoinmune' },
  { value: 'Derrame Pleural secundario a Falla cardiaca', label: 'Derrame Pleural secundario a Falla cardiaca' },
  { value: 'Derrame Pleural secundario a Falla renal', label: 'Derrame Pleural secundario a Falla renal' },
  { value: 'Derrame Pleural secundario a Insuficiencia hepática', label: 'Derrame Pleural secundario a Insuficiencia hepática' },
  { value: 'Derrame pleural masivo', label: 'Derrame pleural masivo' },
  { value: 'Derrame pleural', label: 'Derrame pleural' },
  { value: 'Desviación del tabique nasal', label: 'Desviación del tabique nasal' },
  { value: 'Diabetes Mellitus gestacional', label: 'Diabetes Mellitus gestacional' },
  { value: 'Diabetes Mellitus tipo 1', label: 'Diabetes Mellitus tipo 1' },
  { value: 'Diabetes Mellitus tipo 2', label: 'Diabetes Mellitus tipo 2' },
  { value: 'Discinesia ciliar', label: 'Discinesia ciliar' },
  { value: 'Distrofia fascioescapulohumeral', label: 'Distrofia fascioescapulohumeral' },
  { value: 'Distrofia miotónica de Steinert', label: 'Distrofia miotónica de Steinert' },
  { value: 'Distrofia muscular de Becker', label: 'Distrofia muscular de Becker' },
  { value: 'Distrofia muscular de Cintura escapulohumeral o pélvica', label: 'Distrofia muscular de Cintura escapulohumeral o pélvica' },
  { value: 'Distrofia muscular de Duchenne', label: 'Distrofia muscular de Duchenne' },
  { value: 'Diverticulosis', label: 'Diverticulosis' },
  { value: 'Edema pulmonar', label: 'Edema pulmonar' },
  { value: 'Edema pulmonar', label: 'Edema pulmonar' },
  { value: 'Embolia pulmonar (Aérea)', label: 'Embolia pulmonar (Aérea)' },
  { value: 'Embolia pulmonar (Grasa)', label: 'Embolia pulmonar (Grasa)' },
  { value: 'Embolia pulmonar asociada a Trombosis venosa profunda', label: 'Embolia pulmonar asociada a Trombosis venosa profunda' },
  { value: 'Embolia pulmonar', label: 'Embolia pulmonar' },
  { value: 'Empiema', label: 'Empiema' },
  { value: 'Enfermedad Pulmonar Multinodular', label: 'Enfermedad Pulmonar Multinodular' },
  { value: 'Enfermedad Renal Crónica (ERC)', label: 'Enfermedad Renal Crónica (ERC)' },
  { value: 'Enfermedad de Alzheimer', label: 'Enfermedad de Alzheimer' },
  { value: 'Enfermedad de Crohn', label: 'Enfermedad de Crohn' },
  { value: 'Enfermedad de Parkinson', label: 'Enfermedad de Parkinson' },
  { value: 'Enfermedad de Pompe', label: 'Enfermedad de Pompe' },
  { value: 'Enfermedad mixta del tejido conectivo', label: 'Enfermedad mixta del tejido conectivo' },
  { value: 'Enfermedad por reflujo gastroesofágico', label: 'Enfermedad por reflujo gastroesofágico' },
  { value: 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda', label: 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda' },
  { value: 'Enfermedad pulmonar obstructiva crónica secundaria a Tabaquismo', label: 'Enfermedad pulmonar obstructiva crónica secundaria a tabaquismo' },
  { value: 'Enfermedad pulmonar obstructiva crónica secundaria a exposicion a biomasa', label: 'Enfermedad pulmonar obstructiva crónica secundaria a exposicion a biomasa' },
  { value: 'Enfermedad pulmonar obstructiva crónica', label: 'Enfermedad pulmonar obstructiva crónica' },
  { value: 'Enfermedad valvular (estenosis aórtica, estenosis mitral, insuficiencia aortica, insuficiencia mitral)', label: 'Enfermedad valvular (estenosis aórtica, estenosis mitral, insuficiencia aortica, insuficiencia mitral)' },
  { value: 'Enfermedad ácido péptica', label: 'Enfermedad ácido péptica' },
  { value: 'Enfisema centrolobulillar', label: 'Enfisema centrolobulillar' },
  { value: 'Enfisema panlobulillar', label: 'Enfisema panlobulillar' },
  { value: 'Epilepsia', label: 'Epilepsia' },
  { value: 'Esclerosis lateral amiotrófica', label: 'Esclerosis lateral amiotrófica' },
  { value: 'Esclerosis sistémica', label: 'Esclerosis sistémica' },
  { value: 'Estenosis multisegmentaria de la vía aérea', label: 'Estenosis multisegmentaria de la vía aérea' },
  { value: 'Estenosis subglótica tras un procedimiento', label: 'Estenosis subglótica tras un procedimiento' },
  { value: 'Estenosis subglótica', label: 'Estenosis subglótica' },
  { value: 'Estenosis traqueal tras un procedimiento', label: 'Estenosis traqueal tras un procedimiento' },
  { value: 'Estenosis traqueal', label: 'Estenosis traqueal' },
  { value: 'Evento vascular cerebral', label: 'Evento vascular cerebral' },
  { value: 'Faringitis aguda', label: 'Faringitis aguda' },
  { value: 'Fibrilación auricular', label: 'Fibrilación auricular' },
  { value: 'Fibrosis quística', label: 'Fibrosis quística' },
  { value: 'Fibrotórax', label: 'Fibrotórax' },
  { value: 'Funcionamiento defectuoso de traqueostomía', label: 'Funcionamiento defectuoso de traqueostomía' },
  { value: 'Granulomatosis poliangeitis (Wegener)', label: 'Granulomatosis poliangeitis (Wegener)' },
  { value: 'Hemoptisis asociada a Malformación arteriovenosa', label: 'Hemoptisis asociada a Malformación arteriovenosa' },
  { value: 'Hemoptisis asociada a cavitación', label: 'Hemoptisis asociada a cavitación' },
  { value: 'Hemoptisis asociada a tumor abscedado', label: 'Hemoptisis asociada a tumor abscedado' },
  { value: 'Hemoptisis', label: 'Hemoptisis' },
  { value: 'Hemotórax', label: 'Hemotórax' },
  { value: 'Hernia hiatal tipo 1', label: 'Hernia hiatal tipo 1' },
  { value: 'Hernia hiatal tipo 2', label: 'Hernia hiatal tipo 2' },
  { value: 'Hernia hiatal tipo 3', label: 'Hernia hiatal tipo 3' },
  { value: 'Hiperaldosteronismo', label: 'Hiperaldosteronismo' },
  { value: 'Hipertension Arterial Sistémica (HAS)', label: 'Hipertension Arterial Sistémica (HAS)' },
  { value: 'Hipertension Pulmonar (HP) grupo 1', label: 'Hipertension Pulmonar (HP) grupo 1' },
  { value: 'Hipertension Pulmonar (HP) grupo 2', label: 'Hipertension Pulmonar (HP) grupo 2' },
  { value: 'Hipertension Pulmonar (HP) grupo 3', label: 'Hipertension Pulmonar (HP) grupo 3' },
  { value: 'Hipertension Pulmonar (HP) grupo 4', label: 'Hipertension Pulmonar (HP) grupo 4' },
  { value: 'Hipertension Pulmonar (HP) grupo 5', label: 'Hipertension Pulmonar (HP) grupo 5' },
  { value: 'Hipertensión Arterial Sistémica', label: 'Hipertensión Arterial Sistémica' },
  { value: 'Hipertrofia de los cornetes nasales', label: 'Hipertrofia de los cornetes nasales' },
  { value: 'Hipocalemina', label: 'Hipocalemina' },
  { value: 'Hipotirodismo', label: 'Hipotirodismo' },
  { value: 'Insuficiencia cardiaca', label: 'Insuficiencia cardiaca' },
  { value: 'Laringitis crónica o laringotraqueítis', label: 'Laringitis crónica o laringotraqueítis' },
  { value: 'Laringitis o traqueítis aguda', label: 'Laringitis o traqueítis aguda' },
  { value: 'Laringitis obstructiva aguda o epiglotitis', label: 'Laringitis obstructiva aguda o epiglotitis' },
  { value: 'Laringofaringitis aguda', label: 'Laringofaringitis aguda' },
  { value: 'Lesión Renal Aguda (LRA)', label: 'Lesión Renal Aguda (LRA)' },
  { value: 'Lesión pulmonar aguda relacionada a transfusión', label: 'Lesión pulmonar aguda relacionada a transfusión' },
  { value: 'Lupus eritematoso', label: 'Lupus eritematoso' },
  { value: 'Miocardiopatia dilatada', label: 'Miocardiopatia dilatada' },
  { value: 'Miocardiopatia hipertensiva', label: 'Miocardiopatia hipertensiva' },
  { value: 'Miocardiopatia hipertrófica', label: 'Miocardiopatia hipertrófica' },
  { value: 'Miosistis/dermatomiosistis', label: 'Miosistis/dermatomiosistis' }, 
  { value: 'Nasofaringitis aguda', label: 'Nasofaringitis aguda' },
  { value: 'Neoplasia de comportamiento incierto del sistema respiratorio', label: 'Neoplasia de comportamiento incierto del sistema respiratorio' },
  { value: 'Neoplasia endocrina múltiple', label: 'Neoplasia endocrina múltiple' },
  { value: 'Neoplasia maligna del sistema respiratorio', label: 'Neoplasia maligna del sistema respiratorio' },
  { value: 'Neumonía Adquirida en el hospital', label: 'Neumonía Adquirida en el hospital' },
  { value: 'Neumonía Adquirida en la Comunidad (NAC)', label: 'Neumonía Adquirida en la Comunidad (NAC)' },
  { value: 'Neumonía Asociada a la Atención Médica', label: 'Neumonía Asociada a la Atención Médica' },
  { value: 'Neumonía Asociada a la Ventilación', label: 'Neumonía Asociada a la Ventilación' },
  { value: 'Neumonía Intersticial Difusa (NID) - Bronquiolitis respiratoria/EPID', label: 'Neumonía Intersticial Difusa (NID) - Bronquiolitis respiratoria/EPID' },
  { value: 'Neumonía Intersticial Difusa (NID) - Fibroelastosis pleuropulmonar', label: 'Neumonía Intersticial Difusa (NID) - Fibroelastosis pleuropulmonar' },
  { value: 'Neumonía Intersticial Difusa (NID) - Fibrosis Pulmonar Idiopática (FPI)', label: 'Neumonía Intersticial Difusa (NID) - Fibrosis Pulmonar Idiopática (FPI)' },
  { value: 'Neumonía Intersticial Difusa (NID) - Linfoidea Secundaria a Síndrome de Sjogren', label: 'Neumonía Intersticial Difusa (NID) - Linfoidea Secundaria a Síndrome de Sjogren' },
  { value: 'Neumonía Intersticial Difusa (NID) - NINE Idiopática', label: 'Neumonía Intersticial Difusa (NID) - NINE Idiopática' },
  { value: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Artritis reumatoide', label: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Artritis reumatoide' },
  { value: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Esclerosis sistémica', label: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Esclerosis sistémica' },
  { value: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Miositis', label: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Miositis' },
  { value: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Síndrome de Sjogren', label: 'Neumonía Intersticial Difusa (NID) - NINE Secundaria a Síndrome de Sjogren' },
  { value: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Artritis reumatoide', label: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Artritis reumatoide' },
  { value: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Esclerosis sistémica', label: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Esclerosis sistémica' },
  { value: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Vasculitis ANCA', label: 'Neumonía Intersticial Difusa (NID) - NIU Secundaria a Vasculitis ANCA' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonia Intersticial Descamativa', label: 'Neumonía Intersticial Difusa (NID) - Neumonia Intersticial Descamativa' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonitis por Hipersensibilidad', label: 'Neumonía Intersticial Difusa (NID) - Neumonitis por Hipersensibilidad' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonía Eosinofílica', label: 'Neumonía Intersticial Difusa (NID) - Neumonía Eosinofílica' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada Secundaria a Síndrome anti MDA5', label: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada Secundaria a Síndrome anti MDA5' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada Secundaria a Síndrome antisintetasa', label: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada Secundaria a Síndrome antisintetasa' },
  { value: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada', label: 'Neumonía Intersticial Difusa (NID) - Neumonía Organizada' },
  { value: 'Neumonía Intersticial Difusa (NID) - Proteinosis alveolar', label: 'Neumonía Intersticial Difusa (NID) - Proteinosis alveolar' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - FPI', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - FPI' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Hemorragia alveolar', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Hemorragia alveolar' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - NINE', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - NINE' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis Hipersensibilidad (NH)', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis Hipersensibilidad (NH)' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis Lúpica', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis Lúpica' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis por medicamentos', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonitis por medicamentos' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonía Organizada Síndrome anti MDA5', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Neumonía Organizada Síndrome anti MDA5' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada - Proteinosis alveolar', label: 'Neumonía Intersticial Difusa (NID) Exacerbada - Proteinosis alveolar' },
  { value: 'Neumonía Intersticial Difusa (NID) Exacerbada', label: 'Neumonía Intersticial Difusa (NID) Exacerbada' },
  { value: 'Neumonía Intersticial Difusa (NID)', label: 'Neumonía Intersticial Difusa (NID)' },
  { value: 'Neumonía atípica', label: 'Neumonía atípica' },
  { value: 'Neumonía bactacteriana', label: 'Neumonía bactacteriana' },
  { value: 'Neumonía cavitaria', label: 'Neumonía cavitaria' },
  { value: 'Neumonía del paciente inmunosuprimido', label: 'Neumonía del paciente inmunosuprimido' },
  { value: 'Neumonía eosinofílica', label: 'Neumonía eosinofílica' },
  { value: 'Neumonía focal', label: 'Neumonía focal' },
  { value: 'Neumonía intersticial aguda (NIA)', label: 'Neumonía intersticial aguda (NIA)' },
  { value: 'Neumonía lipoidea', label: 'Neumonía lipoidea' },
  { value: 'Neumonía lúpica', label: 'Neumonía lúpica' },
  { value: 'Neumonía necrotizante', label: 'Neumonía necrotizante' },
  { value: 'Neumonía neonatal', label: 'Neumonía neonatal' },
  { value: 'Neumonía organizada', label: 'Neumonía organizada' },
  { value: 'Neumonía por Broncoaspiración', label: 'Neumonía por Broncoaspiración' },
  { value: 'Neumonía post-obstructiva', label: 'Neumonía post-obstructiva' },
  { value: 'Neumonía viral', label: 'Neumonía viral' },
  { value: 'Neumotórax Espontaneo primario', label: 'Neumotórax Espontaneo primario' },
  { value: 'Neumotórax Espontaneo secundario', label: 'Neumotórax Espontaneo secundario' },
  { value: 'Neumotórax Iatrogénico', label: 'Neumotórax Iatrogénico' },
  { value: 'Neumotórax Traumático', label: 'Neumotórax Traumático' },
  { value: 'Neumotórax', label: 'Neumotórax' },
  { value: 'Neutropenia febril', label: 'Neutropenia febril' },
  { value: 'Osteoartritis degenerativa', label: 'Osteoartritis degenerativa' },
  { value: 'Parálisis cerebral infantil', label: 'Parálisis cerebral infantil' },
  { value: 'Policondritis recidivante', label: 'Policondritis recidivante' },
  { value: 'Poliposis nasal', label: 'Poliposis nasal' },
  { value: 'Quilotórax', label: 'Quilotórax' },
  { value: 'Quiste o mucocele de nariz o seno paranasal', label: 'Quiste o mucocele de nariz o seno paranasal' },
  { value: 'Rinitis alérgica o vasomotora', label: 'Rinitis alérgica o vasomotora' },
  { value: 'Rinitis, nasofaringitis o faringitis crónica', label: 'Rinitis, nasofaringitis o faringitis crónica' },
  { value: 'Derrame Pericárdico', label: 'Derrame Pericárdico' },
  { value: 'Insuficiencia Respiratoria tipo I', label: 'Insuficiencia Respiratoria tipo I' },
  { value: 'Insuficiencia Respiratoria tipo II', label: 'Insuficiencia Respiratoria tipo II' },
  { value: 'Sarcoma', label: 'Sarcoma' },
  { value: 'Sepsis grave', label: 'Sepsis grave' },
  { value: 'Sepsis', label: 'Sepsis' },
  { value: 'Sindrome de Apnea Obstuctiva del Sueño (SAOS)', label: 'Sindrome de Apnea Obstuctiva del Sueño (SAOS)' },
  { value: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Hipertrofia amigdalina', label: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Hipertrofia amigdalina' },
  { value: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Malformación craneofacial', label: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Malformación craneofacial' },
  { value: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Obesidad', label: 'Sindrome de apnea obstructiva del sueño (SAOS) asociado a Obesidad' },
  { value: 'Sinusitis aguda', label: 'Sinusitis aguda' },
  { value: 'Sinusitis crónica', label: 'Sinusitis crónica' },
  { value: 'Sospecha de neoplasia del sistema respiratorio', label: 'Sospecha de neoplasia del sistema respiratorio' },
  { value: 'Síndrome Paraneoplásico', label: 'Síndrome Paraneoplásico' },
  { value: 'Síndrome antisintetasa', label: 'Síndrome antisintetasa' },
  { value: 'Síndrome coronario agudo', label: 'Síndrome coronario agudo' },
  { value: 'Síndrome de Churg Strauss', label: 'Síndrome de Churg Strauss' },
  { value: 'Síndrome de Insuficiencia Respiratoria Aguda (SIRA)', label: 'Síndrome de Insuficiencia Respiratoria Aguda (SIRA)' },
  { value: 'Síndrome de Obesidad Hipoventilación  (SOH)', label: 'Síndrome de Obesidad Hipoventilación  (SOH)' },
  { value: 'Síndrome de Sjogren', label: 'Síndrome de Sjogren' },
  { value: 'Síndrome de secreción inapropiada de hormona antidiurética', label: 'Síndrome de secreción inapropiada de hormona antidiurética' },
  { value: 'Síndrome del seno silencioso', label: 'Síndrome del seno silencioso' },
  { value: 'Síndrome miasténico', label: 'Síndrome miasténico' },
  { value: 'Síndrome post-paro cardíaco', label: 'Síndrome post-paro cardíaco' },
  { value: 'Trastorno de la motilidad esofágica', label: 'Trastorno de la motilidad esofágica' },
  { value: 'Tumor endobronquial', label: 'Tumor endobronquial' },
  { value: 'Tumor glótico', label: 'Tumor glótico' },
  ];