
export const socialOptionsLengua = [
  { value: 'No', label: 'No' },
  { value: 'Akateko', label: 'Akateko' },
  { value: 'Amuzgo', label: 'Amuzgo' },
  { value: 'Awakateko', label: 'Awakateko' },
  { value: 'Ayapaneco', label: 'Ayapaneco' },
  { value: 'Cora', label: 'Cora' },
  { value: 'Cucapá', label: 'Cucapá' },
  { value: 'Cuicateco', label: 'Cuicateco' },
  { value: 'Chatino', label: 'Chatino' },
  { value: 'Chichimeco Jonaz', label: 'Chichimeco Jonaz' },
  { value: 'Chinanteco', label: 'Chinanteco' },
  { value: 'Chocholteco', label: 'Chocholteco' },
  { value: 'Chontal de oaxaca', label: 'Chontal de oaxaca' },
  { value: 'Chontal de tabasco', label: 'Chontal de tabasco' },
  { value: 'Chuj', label: 'Chuj' },
  { value: 'Chol', label: 'Ch\'ol' },
  { value: 'Guarijío', label: 'Guarijío' },
  { value: 'Huasteco', label: 'Huasteco' },
  { value: 'Huave', label: 'Huave' },
  { value: 'Huichol', label: 'Huichol' },
  { value: 'Ixcateco', label: 'Ixcateco' },
  { value: 'Ixil', label: 'Ixil' },
  { value: 'Jakalteko', label: 'Jakalteko' },
  { value: 'Kaqchikel', label: 'Kaqchikel' },
  { value: 'Kickapoo', label: 'Kickapoo' },
  { value: 'Kiliwa', label: 'Kiliwa' },
  { value: 'Kumiai', label: 'Kumiai' },
  { value: 'Kuahl', label: 'Ku\'ahl' },
  { value: 'Kiche', label: 'K\'iche\'' },
  { value: 'Lacandón', label: 'Lacandón' },
  { value: 'Mam', label: 'Mam' },
  { value: 'Matlatzinca', label: 'Matlatzinca' },
  { value: 'Maya', label: 'Maya' },
  { value: 'Mayo', label: 'Mayo' },
  { value: 'Mazahua', label: 'Mazahua' },
  { value: 'Mazateco', label: 'Mazateco' },
  { value: 'Mixe', label: 'Mixe' },
  { value: 'Mixteco', label: 'Mixteco' },
  { value: 'Náhuatl', label: 'Náhuatl' },
  { value: 'Oluteco', label: 'Oluteco' },
  { value: 'Otomí', label: 'Otomí' },
  { value: 'Paipai', label: 'Paipai' },
  { value: 'Pame', label: 'Pame' },
  { value: 'Pápago', label: 'Pápago' },
  { value: 'Pima', label: 'Pima' },
  { value: 'Popoloca', label: 'Popoloca' },
  { value: 'Popoluca de la sierra', label: 'Popoluca de la sierra' },
  { value: 'Qatok', label: 'Qato\'k' },
  { value: 'Qanjobal', label: 'Q\'anjob\'al' },
  { value: 'Qeqchí', label: 'Q\'eqchí' },
  { value: 'Sayulteco', label: 'Sayulteco' },
  { value: 'Seri', label: 'Seri' },
  { value: 'Tarahumara', label: 'Tarahumara' },
  { value: 'Tarasco', label: 'Tarasco' },
  { value: 'Teko', label: 'Teko' },
  { value: 'Tepehua', label: 'Tepehua' },
  { value: 'Tepehuano del norte', label: 'Tepehuano del norte' },
  { value: 'Tepehuano del sur', label: 'Tepehuano del sur' },
  { value: 'Texistepequeño', label: 'Texistepequeño' },
  { value: 'Tlahuica', label: 'Tlahuica' },
  { value: 'Tlapaneco', label: 'Tlapaneco' },
  { value: 'Tojolabal', label: 'Tojolabal' },
  { value: 'Totonaco', label: 'Totonaco' },
  { value: 'Triqui', label: 'Triqui' },
  { value: 'Tzeltal', label: 'Tzeltal' },
  { value: 'Tsotsil', label: 'Tsotsil' },
  { value: 'Yaqui', label: 'Yaqui' },
  { value: 'Zapoteco', label: 'Zapoteco' },
  { value: 'Zoque', label: 'Zoque' },
  
    // Más opciones...
  ];


export const socialOptionsReligion = [
  { value: 'Ninguna', label: 'Ninguna' },
  { value: 'Creyente', label: 'Creyente' },
  { value: 'Católica', label: 'Católica' },
  { value: 'Cristiana', label: 'Cristiana' },
  { value: 'Testigo de Jehová', label: 'Testigo de Jehová' },
  { value: 'Ortodoxa', label: 'Ortodoxa' },
  { value: 'Anglicana', label: 'Anglicana' },
  { value: 'Bautista', label: 'Bautista' },
  { value: 'Luterana', label: 'Luterana' },
  { value: 'Metodista', label: 'Metodista' },
  { value: 'Presbiteriana', label: 'Presbiteriana' },
  { value: 'Adventista del Séptimo Día', label: 'Adventista del Séptimo Día' },
  { value: 'Pentecostal', label: 'Pentecostal' },
  { value: 'Asambleas de Dios', label: 'Asambleas de Dios' },
  { value: 'Iglesia de Cristo', label: 'Iglesia de Cristo' },
  { value: 'Iglesia de Dios', label: 'Iglesia de Dios' },
  { value: 'Menonita', label: 'Menonita' },
  { value: 'Mormón', label: 'Mormón' },
  { value: 'Quaker', label: 'Quaker' },
  { value: 'Iglesia del Nazareno', label: 'Iglesia del Nazareno' },
  { value: 'Universalista Unitaria', label: 'Universalista Unitaria' },
  { value: 'Islam', label: 'Islam' },
  { value: 'Hinduismo', label: 'Hinduismo' },
  { value: 'Budismo', label: 'Budismo' },
  { value: 'Sijismo', label: 'Sijismo' },
  { value: 'Judaísmo', label: 'Judaísmo' },
  { value: 'Bahaísmo', label: 'Bahaísmo' },
  { value: 'Confucianismo', label: 'Confucianismo' },
  { value: 'Taoísmo', label: 'Taoísmo' },
  { value: 'Jainismo', label: 'Jainismo' },
  { value: 'Shinto', label: 'Shinto' },
  { value: 'Zoroastrismo', label: 'Zoroastrismo' },
  { value: 'Animismo', label: 'Animismo' },
  { value: 'Paganismo', label: 'Paganismo' },
  { value: 'Wicca', label: 'Wicca' },
  { value: 'Rastafarianismo', label: 'Rastafarianismo' },
  { value: 'Tenrikyo', label: 'Tenrikyo' },
  { value: 'Caodaísmo', label: 'Caodaísmo' },
  { value: 'Vudú', label: 'Vudú' },
  { value: 'Santería', label: 'Santería' },
  { value: 'Neopaganismo', label: 'Neopaganismo' },
  

];



export const socialOptionsExpuesto = [
{ value: 'Ácido acético', label: 'Ácido acético' },
{ value: 'Ácido sulfúrico', label: 'Ácido sulfúrico' },
{ value: 'Amoniaco', label: 'Amoniaco' },
{ value: 'Aparatos de aire acondicionado o calefacción en el hogar o el trabajo', label: 'Aparatos de aire acondicionado o calefacción en el hogar o el trabajo' },
{ value: 'Arena, cal, cemento, yeso o polvos similares', label: 'Arena, cal, cemento, yeso o polvos similares' },
{ value: 'Asbesto', label: 'Asbesto' },
{ value: 'Bagazo', label: 'Bagazo' },
{ value: 'Berilio', label: 'Berilio' },
{ value: 'Cloro', label: 'Cloro' },
{ value: 'Cortinas de baño con moho', label: 'Cortinas de baño con moho' },
{ value: 'Cosechas contaminadas', label: 'Cosechas contaminadas' },
{ value: 'Dioxido de nitrógeno', label: 'Dioxido de nitrógeno' },
{ value: 'Espuma de Poliuretano, pinturas en spray, pegamentos, adhesivos', label: 'Espuma de Poliuretano, pinturas en spray, pegamentos, adhesivos' },
{ value: 'Éteres de glicol', label: 'Éteres de glicol' },
{ value: 'Condimentos', label: 'Condimentos' },
{ value: 'Fertilizantes', label: 'Fertilizantes' },
{ value: 'Hollín', label: 'Hollín' },
{ value: 'Fardos de turba', label: 'Fardos de turba' },
{ value: 'Formalina', label: 'Formalina' },
{ value: 'Fuentes y humidificadores', label: 'Fuentes y humidificadores' },
{ value: 'Gases de diésel', label: 'Gases de diésel' },
{ value: 'Gases metano, radón', label: 'Gases metano, radón' },
{ value: 'Granos o semillas contaminadas', label: 'Granos o semillas contaminadas' },
{ value: 'Heno contaminado', label: 'Heno contaminado' },
{ value: 'Insecticidas organofosforados', label: 'Insecticidas organofosforados' },
{ value: 'Instrumentos de viento', label: 'Instrumentos de viento' },
{ value: 'Isocionatos', label: 'Isocionatos' },
{ value: 'Invernadero', label: 'Invernadero' },
{ value: 'Lavador de quesos', label: 'Lavador de quesos' },
{ value: 'Madera con hongos', label: 'Madera con hongos' },
{ value: 'Manipulación de Baterías', label: 'Manipulación de Baterías' },
{ value: 'Materiales para prótesis dentarias', label: 'Materiales para prótesis dentarias' },
{ value: 'Metales pesados mercurio, plomo, cadmio, cobre, cromo, talio, zinc', label: 'Metales pesados mercurio, plomo, cadmio, cobre, cromo, talio, zinc' },
{ value: 'Mezcla de cobre sulfatos', label: 'Mezcla de cobre sulfatos' },
{ value: 'Moho', label: 'Moho' },
{ value: 'Mostaza, fosgeno', label: 'Mostaza, fosgeno' },
{ value: 'Olor a humedad en la casa o trabajo', label: 'Olor a humedad en la casa o trabajo' },
{ value: 'Óxido de nitrógeno', label: 'Óxido de nitrógeno' },
{ value: 'Pieles de animales', label: 'Pieles de animales' },
{ value: 'Podología, manicuria', label: 'Podología, manicuria' },
{ value: 'Producción de hilos', label: 'Producción de hilos' },
{ value: 'Productor de salames', label: 'Productor de salames' },
{ value: 'Productores de lácteos', label: 'Productores de lácteos' },
{ value: 'Plumas de aves en almohadas, cobertores, sillones, decoraciones', label: 'Plumas de aves en almohadas, cobertores, sillones, decoraciones' },
{ value: 'Realiza Composta', label: 'Realiza Composta' },
{ value: 'Resinas', label: 'Resinas' },
{ value: 'Sílice', label: 'Sílice' },
{ value: 'Solventes y aromatizantes', label: 'Solventes y aromatizantes' },
{ value: 'Telas algodón, seda, o similares', label: 'Telas algodón, seda, o similares' },
{ value: 'Tiene plantación de hongos shitake', label: 'Tiene plantación de hongos shitake' },
{ value: 'Tiene plantas y maneja tierra, fertilizantes', label: 'Tiene plantas y maneja tierra, fertilizantes' },
{ value: 'Trabaja con alimento para pájaros o peces', label: 'Trabaja con alimento para pájaros o peces' },
{ value: 'Trabaja con detergentes, agentes de limpieza biológicos', label: 'Trabaja con detergentes, agentes de limpieza biológicos' },
{ value: 'Trabaja con harina de trigo', label: 'Trabaja con harina de trigo' },
{ value: 'Trabaja con maderas o en aserraderos', label: 'Trabaja con maderas o en aserraderos' },
{ value: 'Trabaja con pinturas o barnices', label: 'Trabaja con pinturas o barnices' },
{ value: 'Trabaja con sprays de espuma', label: 'Trabaja con sprays de espuma' },
{ value: 'Trabaja o está expuesto a fluidos metálicos', label: 'Trabaja o está expuesto a fluidos metálicos' },
{ value: 'Viaje en el último año a zonas endémicas de coccidioidomicosis', label: 'Viaje en el último año a zonas endémicas de coccidioidomicosis' },
{ value: 'Ninguna', label: 'Ninguna' },
];
