
export const microorganismoOptions = [
    { value: 'Acinetobacter', label: 'Acinetobacter' },
    { value: 'Burkholderia', label: 'Burkholderia' },
    { value: 'Chlamydophila pneumoniae', label: 'Chlamydophila pneumoniae' },
    { value: 'Clostridium difficile', label: 'Clostridium difficile' },
    { value: 'Enterobacter spp', label: 'Enterobacter spp' },
    { value: 'Escherichia coli', label: 'Escherichia coli' },
    { value: 'Haemophilus influenzae', label: 'Haemophilus influenzae' },
    { value: 'Klebsiella', label: 'Klebsiella' },
    { value: 'Legionella', label: 'Legionella' },
    { value: 'Moraxella catarrhalis', label: 'Moraxella catarrhalis' },
    { value: 'Mycobacterium tuberculosis', label: 'Mycobacterium tuberculosis' },
    { value: 'Mycobacterias No tuberculosis', label: 'Mycobacterias No tuberculosis' },
    { value: 'Mycoplasma pneumoniae', label: 'Mycoplasma pneumoniae' },
    { value: 'Neisseria meningitidis', label: 'Neisseria meningitidis' },
    { value: 'Pseudomonas aeruginosa', label: 'Pseudomonas aeruginosa' },
    { value: 'Serratia', label: 'Serratia' },
    { value: 'Staphylococcus aureus', label: 'Staphylococcus aureus' },
    { value: 'Stenotrophomonas', label: 'Stenotrophomonas' },
    { value: 'Streptococcus agalactiae', label: 'Streptococcus agalactiae' },
    { value: 'Streptococcus pneumoniae', label: 'Streptococcus pneumoniae' },
    { value: 'Streptococcus pyogenes', label: 'Streptococcus pyogenes' },

    { value: 'Coronavirus', label: 'Coronavirus' },
    { value: 'Coronavirus SARS-CoV-2', label: 'Coronavirus SARS-CoV-2' },
    { value: 'Coronavirus 229E', label: 'Coronavirus 229E' },
    { value: 'Coronavirus NL63', label: 'Coronavirus NL63' },
    { value: 'Coronavirus OC43', label: 'Coronavirus OC43' },
    { value: 'Coronavirus HKU1', label: 'Coronavirus HKU1' },
    { value: 'Enterovirus/Rinovirus', label: 'Enterovirus/Rinovirus' },
    { value: 'Influenza A', label: 'Influenza A' },
    { value: 'Influenza A H1N1', label: 'Influenza A H1N1' },
    { value: 'Influenza A H3N2', label: 'Influenza A H3N2' },
    { value: 'Influenza B', label: 'Influenza B' },
    { value: 'Metapneumovirus', label: 'Metapneumovirus' },
    { value: 'Parainfluenza 1', label: 'Parainfluenza 1' },
    { value: 'Parainfluenza 2', label: 'Parainfluenza 2' },
    { value: 'Parainfluenza 3', label: 'Parainfluenza 3' },
    { value: 'Parainfluenza 4', label: 'Parainfluenza 4' },
    { value: 'Virus de Epstein-Barr', label: 'Virus de Epstein-Barr' },
    { value: 'Virus Hepatitis B', label: 'Virus Hepatitis B' },
    { value: 'Virus Hepatitis C', label: 'Virus Hepatitis C' },
    { value: 'Virus Herpes Simple', label: 'Virus Herpes Simple' },
    { value: 'Virus Herpes Zoster', label: 'Virus Herpes Zoster' },
    { value: 'VIH', label: 'VIH' },
    { value: 'Virus Sincitial Respiratorio', label: 'Virus Sincitial Respiratorio' },

    { value: 'Aspergillus', label: 'Aspergillus' },
    { value: 'Blastomyces dermatitidis', label: 'Blastomyces dermatitidis' },
    { value: 'Candida', label: 'Candida' },
    { value: 'Coccidioides immitis', label: 'Coccidioides immitis' },
    { value: 'Cryptococcus neoformans', label: 'Cryptococcus neoformans' },
    { value: 'Histoplasma capsulatum', label: 'Histoplasma capsulatum' },
    { value: 'Mucorales', label: 'Mucorales' },
    { value: 'Pneumocystis jirovecii', label: 'Pneumocystis jirovecii' },
 
    // Más opciones...
  ];